### PR TITLE
[Access] Add heartbeat interval to providers

### LINKED ISSUE #7080: [Access] `heartbeat_interval` argument is missing in events/account statuses WebSocket data providers
## 🐞 Bug Report

The `heartbeat_interval` argument is missing in events/account statuses data providers, and the default heartbeat interval of 1 block is used in both data providers.

## Expected behaviour

A `heartbeat_interval` argument should be supported

### PR DESCRIPTION
**Pull request by illia-malachyn**
Closes #7080 
Branched off #7066 

Parse `heartbeat_interval` from args and reset one provided by the websocket controller.
Add test for invalid `heartbeat_interval` arg.

### CODE REVIEW

File: engine/access/rest/websockets/data_providers/account_statuses_provider.go [hunk 1]
```diff
@@ -169,14 +186,29 @@ func parseAccountStatusesArguments(
 	if accountAddressesIn, ok := arguments["account_addresses"]; ok && accountAddressesIn != "" {
 		accountAddresses, ok = accountAddressesIn.([]string)
 		if !ok {
-			return args, fmt.Errorf("'account_addresses' must be an array of string")
+			return accountStatusesArguments{}, fmt.Errorf("'account_addresses' must be an array of string")
 		}
 	}
 
+	var heartbeatInterval uint64
+	if heartbeatIntervalIn, ok := arguments["heartbeat_interval"]; ok && heartbeatIntervalIn != "" {
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/account_statuses_provider.go:194]: consider
```golang
func parseArg[T any](field string, arguments map[string]interface{}) (parsed T, err error) {
	value, ok := arguments[field]
	if !ok {
		err = fmt.Errorf("field %s is missing from arguments", field)
		return
	}

	parsed, ok = value.(T)
	if !ok {
		err = fmt.Errorf("field %s is incorrect type %T", field, value)
	}
	return
}
```

File: engine/access/rest/websockets/data_providers/args_validation.go [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package data_providers
+
+import (
+	"fmt"
+)
+
+func ensureAllowedFields(data map[string]interface{}, allowedFields []string) error {
+	fieldsMap := make(map[string]bool, len(allowedFields))
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/args_validation.go:8]: maybe just define `allowedFields` as a map instead of converting?

File: engine/access/rest/websockets/data_providers/send_and_get_transaction_statuses_provider_test.go [hunk 3]
```diff
@@ -79,7 +79,7 @@ func (s *TransactionStatusesProviderSuite) TestSendTransactionStatusesDataProvid
 		{
 			name: "SubscribeTransactionStatusesFromStartBlockID happy path",
 			arguments: models.Arguments{
-				"start_block_id": s.rootBlock.ID().String(),
+				"reference_block_id": s.rootBlock.ID().String(),
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/send_and_get_transaction_statuses_provider_test.go:82]: I don't think this is an argument to SubscribeTransactionStatuses.

**Review by peterargue — APPROVED** [review]
added a couple small comments, but looks good

File: engine/access/rest/websockets/data_providers/send_and_get_transaction_statuses_provider_test.go (hunk 3 above)
Comment (illia-malachyn) [reply engine/access/rest/websockets/data_providers/send_and_get_transaction_statuses_provider_test.go:82]: so, what should i put here ?
