### PR TITLE
Fix and refactor validation logic in data providers 

### LINKED ISSUE #7083: [Access] The "tx_id" argument must be required when subscribing for "transaction_statuses"  topic via WebSockets
## 🐞 Bug Report

When subscribing to "transaction_statuses" like:

```json
{
  "subscription_id": "1",
  "action": "subscribe",
  "topic": "transaction_statuses"    
}
```

or

```json
{
  "subscription_id": "1",
  "action": "subscribe",
  "topic": "transaction_statuses",   
  "arguments": {
    "tx_id": ""
  }
}
```

No error was reported about the missing or empty "tx_id" argument.

## Expected behaviour

Report an error about the missing or empty "tx_id" argument.

### PR DESCRIPTION
**Pull request by illia-malachyn**
Closes #7083 
Branched off #6641 

- fixed a bug where `tx_id` could be empty
- refactored parsing functions 
- add some arguments for subscription in tests for clarity 
- remove validateResponse() function in integration tests to make error messages better

### CODE REVIEW

File: engine/access/rest/websockets/data_providers/events_provider.go [hunk 1]
```diff
@@ -164,41 +163,62 @@ func parseEventsArguments(
...
-		addresses, err = common.ParseInterfaceToStrings(addressesIn)
-		if err != nil {
-			return eventsArguments{}, fmt.Errorf("'addresses' must be an array of string")
-		}
+	rawAddresses, exists := arguments["addresses"]
+	if !exists {
+		return eventsArguments{}, fmt.Errorf("missing 'addresses' field")
+	}
+
+	addresses, isStringArray = rawAddresses.([]string)
```
Comment (illia-malachyn) [inline engine/access/rest/websockets/data_providers/events_provider.go:199]: should use ParseInterfaceToStrings

File: engine/access/rest/websockets/data_providers/events_provider.go [hunk 2]
```diff
@@ -164,41 +163,62 @@ func parseEventsArguments(
...
-		contracts, err = common.ParseInterfaceToStrings(contractsIn)
-		if err != nil {
-			return eventsArguments{}, fmt.Errorf("'contracts' must be an array of string")
-		}
+	rawContracts, exists := arguments["contracts"]
+	if !exists {
+		return eventsArguments{}, fmt.Errorf("missing 'contracts' field")
+	}
+
+	contracts, isStringArray = rawContracts.([]string)
```
Comment (illia-malachyn) [inline engine/access/rest/websockets/data_providers/events_provider.go:215]: same

File: engine/access/rest/websockets/data_providers/account_statuses_provider.go [hunk 3]
```diff
@@ -171,40 +170,54 @@ func parseAccountStatusesArguments(
...
-		err = eventTypes.Parse(result)
-		if err != nil {
-			return accountStatusesArguments{}, fmt.Errorf("invalid 'event_types': %w", err)
-		}
+	eventTypesList, isStringArray := rawEventTypes.([]string)
+	if !isStringArray {
+		return accountStatusesArguments{}, fmt.Errorf("'event_types' must be an array of string")
+	}
+
+	if len(eventTypesList) == 0 {
```
Comment (illia-malachyn) [inline engine/access/rest/websockets/data_providers/account_statuses_provider.go:183]: this is not true. it can be empty

File: engine/access/rest/websockets/data_providers/account_statuses_provider.go [hunk 4]
```diff
@@ -169,42 +167,28 @@ func parseAccountStatusesArguments(
...
-		result, ok := heartbeatIntervalIn.(string)
-		if !ok {
-			return accountStatusesArguments{}, fmt.Errorf("'heartbeat_interval' must be a string")
-		}
-
-		heartbeatInterval, err = util.ToUint64(result)
-		if err != nil {
-			return accountStatusesArguments{}, fmt.Errorf("invalid 'heartbeat_interval': %w", err)
-		}
+	eventTypes, err := parser.NewEventTypes(eventTypeList)
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/account_statuses_provider.go:183]: this validation logic is already done within `NewAccountStatusFilter`, so you don't need to do it initially here. a list of strings is fine

File: engine/access/rest/websockets/data_providers/args_validation.go [hunk 5]
```diff
@@ -2,18 +2,59 @@ package data_providers
...
+	for key := range fields {
+		if _, exists := allowedFields[key]; !exists {
 			return fmt.Errorf("unexpected field: '%s'", key)
 		}
 	}
+
 	return nil
 }
+
+func extractArrayOfStrings(args models.Arguments, name string, required bool) ([]string, error) {
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/args_validation.go:22]: please add unit tests for these methods

File: engine/access/rest/websockets/data_providers/events_provider.go [hunk 6]
```diff
@@ -164,63 +162,47 @@ func parseEventsArguments(
...
+	eventTypesList, err := extractArrayOfStrings(arguments, "event_types", false)
+	if err != nil {
+		return eventsArguments{}, err
+	}
 
-		err = eventTypes.Parse(result)
-		if err != nil {
-			return eventsArguments{}, fmt.Errorf("invalid 'event_types': %w", err)
-		}
+	eventTypes, err := parser.NewEventTypes(eventTypesList)
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/events_provider.go:183]: same comment about validating event types

**Review by peterargue — COMMENTED** [review]
added a few comments, but otherwise looks good

File: engine/access/rest/common/parser/event_type.go [hunk 7]
```diff
@@ -10,6 +10,13 @@ type EventType string
 var basicEventRe = regexp.MustCompile(`[A-Z]\.[a-f0-9]{16}\.[\w+]*\.[\w+]*`)
 var flowEventRe = regexp.MustCompile(`flow\.[\w]*`)
 
+func NewEventType(raw string) (EventType, error) {
+	if !basicEventRe.MatchString(raw) && !flowEventRe.MatchString(raw) {
+		return "", fmt.Errorf("invalid event type format")
+	}
+	return EventType(raw), nil
+}
+
```
Comment (peterargue) [inline engine/access/rest/common/parser/event_type.go:19]: don't look like these are used anymore, let's delete them for now
```suggestion
```

File: engine/access/rest/common/parser/event_type.go [hunk 8]
```diff
@@ -24,6 +31,24 @@ func (e EventType) Flow() string {
...
+		if !uniqueTypes[eType.Flow()] {
+			uniqueTypes[eType.Flow()] = true
+			eventTypes = append(eventTypes, eType)
+		}
+	}
+
+	return eventTypes, nil
+}
+
```
Comment (peterargue) [inline engine/access/rest/common/parser/event_type.go:51]:
```suggestion
```

**Review by peterargue — APPROVED** [review]
looks good

File: engine/access/rest/common/parser/event_type.go (hunk 7 above)
Comment (illia-malachyn) [reply engine/access/rest/common/parser/event_type.go]: I removed the `Parse()` function in favor of this constructor to ensure that an `EventType` is always fully initialized upon creation. This avoids having an intermediate, potentially invalid state and enforces correctness at the point of instantiation.

File: engine/access/rest/websockets/data_providers/unit_test.go [hunk 9]
```diff
@@ -111,3 +111,103 @@ func extractPayload[T any](t *testing.T, v interface{}) (*models.BaseDataProvide
...
+		fields := map[string]interface{}{
+			"start_block_id":     "abc",
+			"start_block_height": 123,
+			"event_types":        []string{"flow.Event"},
+			"account_addresses":  []string{"0x1"},
+			"heartbeat_interval": 10,
+		}
+		if err := ensureAllowedFields(fields, allowedFields); err != nil {
+			t.Errorf("unexpected error: %v", err)
+		}
```
[the remark this answers is not in the document]
Comment (illia-malachyn) [reply engine/access/rest/websockets/data_providers/unit_test.go:136]: I feel like it looks just fine. Also, we don't need an assert here as we don't have more checks after this function call

File: engine/access/rest/common/parser/event_type.go (hunk 8 above)
Comment (illia-malachyn) [reply engine/access/rest/common/parser/event_type.go]: answered above

File: engine/access/rest/websockets/data_providers/unit_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (peterargue) [reply engine/access/rest/websockets/data_providers/unit_test.go:136]: the conventional way to do this is
```golang
err := ensureAllowedFields(fields, allowedFields)
require.NoError(t, err)
```
