### PR TITLE
Fix malleability issues in system collection for scheduled callbacks

### LINKED ISSUE #7749: [Immutable Models M1] Address collection malleability in block computer
## Context
Since last merge from master, illegal mutations were added to the collection in the block computer. These have been temporarily ignored by the linter, but they need to be fixed prior to merge.

See https://github.com/onflow/flow-go/pull/7750/commits/cae8875f04afb3eb0676faf8d2d55a0b27e00d89

### PR DESCRIPTION
**Pull request by tim-barry**
@devbugging Not sure if you can officially review the PR (I can't seem to add you as a reviewer) but I'd appreciate any comments.

Remove modifications to the system collection; instead delay construction of the system collection until we have found all the scheduled callbacks. While some collection metadata (the collection index) is used during execution of the initial process transaction, which determines all the following scheduled callback transactions, the collection itself is unused until the final transaction (the system transaction). If, in the future, execution of the process transaction somehow tries to access the collection, it will panic (which should be caught in tests).

For full context see https://github.com/onflow/flow-go/issues/7749#issuecomment-3229027003

Closes #7749

### CODE REVIEW

**Comment by AlexHentschel** [comment]
I added [this comment](https://github.com/onflow/flow-go/issues/7749#issuecomment-3229691272) on the original issue, discussing fundamental concepts, which the implementation should reflect. 

From my perspective, equally important to an algorithmic solution of the problem is a design, clearly reflecting the fundamentals discussed in [my comment](https://github.com/onflow/flow-go/issues/7749#issuecomment-3229691272):
- [ ] We have a separate data type that "represents a collection" under construction - essentially a builder type in software terminology. While a collection is immutable, the builder provides explicit functionality to extend the thing under construction. 
  - [ ] In our specific case, the builder allows append only. 
         That is because we need to the index of a transaction when we added it to the collection under construction
  - [ ] I would like the builder to explicitly document and enforce this strict bijective relation between added transaction and index. 
  - [ ]  In contrast, the builder should provide _no_ functionality to compute any collection hash (i.e. no ID method) 
  - [ ] and the builder should not provide any functionality to sign the collection, because the build process has to be completed, before we can even thing about signing. 
  - [ ] The builder should offer a build method, which transforms the builder's current transient state into a collection, which by definition is immutable. 
  - [ ] Robustness: imagine built is called and thereafter further mutations of the builder are attempted. It should be impossible that the previously-constructed collection changes as a side effect. One possibility is that the builder just rejects any further mutations after build is called.

File: engine/execution/computation/computer/computer.go [hunk 1]
```diff
@@ -493,19 +490,20 @@ func (e *blockComputer) executeSystemTransactions(
...
+		collectionIndex:     len(rawCollections),
+		CompleteCollection:  nil, // We do not yet know all the scheduled callbacks, so postpone construction of the collection.
 		isSystemTransaction: true,
 	}
 
 	var callbackTxs []*flow.TransactionBody
 
 	if e.vmCtx.ScheduleCallbacksEnabled {
+		// We pass in the systemCollectionInfo here. However, the underlying flow.Collection object
+		// must not be used, because it cannot represent the final state of the system collection.
```
Comment (AlexHentschel) [inline engine/execution/computation/computer/computer.go]: lets make this more rigorous:
* explain the protocol convention and why they are important
```suggestion
		// We pass in the `systemCollectionInfo` here. However, note that at this point, the composition of the system chunk
		// is not yet known. Specifically, the `entity.CompleteCollection` represents the *final* output of a process and is
		// immutable by protocol mandate. If we had a bug in our software that accidentally illegally mutated such stucts,
		// likely the node encountering that bug would misbehave and get slashed, or in the worst case the flow protocol might
		// be compromised. Therefore, we have the rigorous convention in our code base that the `CompleteCollection` is only
		// constructed once the final composition of the system chunk has been determined.
```

**Review by AlexHentschel — APPROVED** [review]
Nice. I like your changes. 

In this case, the builder logic is so simple, that's essentially just calling the `NewCollection` constructor. No builder needed, as far as I can tell.

File: engine/execution/computation/computer/computer.go [hunk 2]
```diff
@@ -493,19 +490,24 @@ func (e *blockComputer) executeSystemTransactions(
...
+		CompleteCollection:  nil, // We do not yet know all the scheduled callbacks, so postpone construction of the collection.
 		isSystemTransaction: true,
 	}
 
 	var callbackTxs []*flow.TransactionBody
 
 	if e.vmCtx.ScheduleCallbacksEnabled {
+		// We pass in the `systemCollectionInfo` here. However, note that at this point, the composition of the system chunk
+		// is not yet known. Specifically, the `entity.CompleteCollection` represents the *final* output of a process and is
+		// immutable by protocol mandate. If we had a bug in our software that accidentally illegally mutated such stucts,
```
Comment (durkmurder) [inline engine/execution/computation/computer/computer.go]:
```suggestion
		// immutable by protocol mandate. If we had a bug in our software that accidentally illegally mutated such structs,
```

**Comment by devbugging** [comment]
LGTM

**Comment by devbugging** [comment]
> I don't particularly like the whole thing is computer. It uses optional fields a lot and makes reasoning about validity a lot harder. For instance:

I agree. Also building system collection with that much complexity doesn't feel anymore in the domain of a block computer, which should only execute the block and whatever the block contains. 
Initially I didn't want to make a huge refactor, but it for sure can be a follow-up based on the current implementation.

**Comment by tim-barry** [comment]
Agreed that it is not easy to reason about validity here due to the missing guarantee etc. A potentially more desirable long-term solution could be to refactor the `collectionInfo` metadata structure used here to reflect actual usage, and separate individual transaction submission from the committing of the collection in the `ResultCollector`.

**Comment by AlexHentschel** [comment]
> In this case guarantee is always empty, which maybe makes sense but again, introduces complexity. The same thing is with `CompleteCollection`. I prefer structures without optional fields, first setting it nil and then passing to some other module and filling the result is the exact anti-pattern that we are trying to avoid. 

I think Yurii is emphasizing a very important point here, which I would like to second. I am cross-posting a slack message which I sent this week to a colleague. It equally applies here: 

---

For flow, **our biggest challenge by far is to manage _intellectual_ complexity in my opinion**. I am encouraging all engineers to write more code and invest runtime resources if that helps us to better modularize the code. My suggestion is to embrace the following design principles:

1. embrace the Linux Philosophy of "Do _one_ thing and do it well"
2. Try to provide the most general solution reasonably possible for a given problem. Even if the current usages of module X don't require edge case y to be handled, its very good practise to still provide an implementation that gracefully handles y. Thereby, as an engineer working with component X, I don't have to constantly pay attention to avoiding edge case y, or worry about in which scenarios I might run into edge case y. 
3. Build small self-contained "lego blocks" and compose them if that's reasonably possible, rather than having one larger component that is not assembled from smaller building blocks. 

Of course, one can take any of those principles to an extreme where they don't make sense anymore. Though, my personal impression is that we are further away from good trade-off, so even if we overcorrected a bit, it would still be a net positive for the project and save us time in the long run (making the system more robust and the code easier to maintain and evolve).

---

What Yurii is pointing out that we are re-using existing data structures for related but somewhat different purposes. This creates intercellular dependencies -- when you work on component X, you have to pay attention to subtle assumptions another component Y makes. _Individually_, each of those dependencies are manageable. But they add up over time and are frequently insufficiently documented. So in a sense, using the same code in an edge-case way in another component is technical debt that I would highly encourage you to avoid for a _complex_  high-assurance system as Flow.
