### PR TITLE
[DataAvailability] Improve ingestion engine error handling

### LINKED ISSUE #7510: [Access] Fix log and continue anti-pattern in ingestion engine
Currently the ingestion engine uses the anti-pattern of logging an error and continuing, instead of properly handling it. Code:
https://github.com/onflow/flow-go/blob/8c30c496cf7b6e3fadad97328697a42f633a4853/engine/access/ingestion/engine.go#L491-L503

Refactor this logic to throw an irrecoverable error for both of these conditions.

https://github.com/onflow/flow-go/blob/8c30c496cf7b6e3fadad97328697a42f633a4853/engine/access/ingestion/engine.go#L494
indicates a bug in the software since the data is passed from a trusted internal component (the entity requester engine)

https://github.com/onflow/flow-go/blob/8c30c496cf7b6e3fadad97328697a42f633a4853/engine/access/ingestion/engine.go#L500
indicates an unexpected issue storing data to the db, which should be handled as an irrecoverable exception

This code is being refactored in https://github.com/onflow/flow-go/pull/7455, so these changes will need to be made to the new module.

### PR DESCRIPTION
**Pull request by illia-malachyn**
Closes #7510

### CODE REVIEW

File: engine/access/ingestion2/collection_syncer.go [hunk 1]
```diff
@@ -0,0 +1,435 @@
...
+// OnCollectionDownloaded indexes and persists a downloaded collection.
+// This function is a callback intended to be used by the requester engine.
+//
+// Note: You might wonder what happens if the ingestion engine crashes,
+// but the requester engine continues to invoke this callback and writes
+// to a closed channel. In our current design, we intentionally ignore such cases.
+//
+// If any engine crashes, we treat it as a sign of possible state corruption,
+// and the node is expected to restart. Thus, this edge case is not handled explicitly.
+func (s *CollectionSyncer) OnCollectionDownloaded(_ flow.Identifier, entity flow.Entity) {
```
Comment (illia-malachyn) [inline engine/access/ingestion2/collection_syncer.go]: this is a main change

File: engine/access/ingestion2/collection_syncer.go [hunk 2]
```diff
@@ -0,0 +1,435 @@
...
+				ctx.Throw(err)
+			}
+
+		case <-updateLastFullBlockHeightTicker.C:
+			err := s.updateLastFullBlockHeight()
+			if err != nil {
+				ctx.Throw(err)
+			}
+
+		case entity := <-s.pendingCollections:
```
Comment (illia-malachyn) [inline engine/access/ingestion2/collection_syncer.go]: here's the place where we handle the processing

File: engine/access/ingestion2/collection_syncer.go [hunk 3]
```diff
@@ -129,6 +133,8 @@ func (s *CollectionSyncer) StartWorkerLoop(ctx irrecoverable.SignalerContext, re
 	updateLastFullBlockHeightTicker := time.NewTicker(fullBlockRefreshInterval)
 	defer updateLastFullBlockHeightTicker.Stop()
 
+	defer close(s.pendingCollections)
```
Comment (Guitarheroua) [inline engine/access/ingestion2/collection_syncer.go]: Maybe worth to put this call before `err := s.requestMissingCollectionsBlocking(requestCtx)`, to definitely close it even if we got an error.

File: engine/access/ingestion2/collection_syncer.go [hunk 4]
```diff
@@ -405,17 +424,14 @@ func (s *CollectionSyncer) findLowestBlockHeightWithMissingCollections(
...
-		s.logger.Error().Msgf("invalid entity type (%T)", entity)
-		return
-	}
-
-	err := indexer.IndexCollection(collection, s.collections, s.transactions, s.logger, s.collectionExecutedMetric)
-	if err != nil {
-		s.logger.Error().Err(err).Msg("could not index collection after it has been downloaded")
-		return
-	}
+	s.pendingCollections <- entity
```
Comment (peterargue) [inline engine/access/ingestion2/collection_syncer.go]: I think this should use a message handler instead of a channel. this allows us to avoid blocking the caller if the main loop is busy, which can happen since it's used for period work as well.

File: engine/access/ingestion2/collection_syncer.go [hunk 5]
```diff
@@ -405,17 +449,17 @@ func (s *CollectionSyncer) findLowestBlockHeightWithMissingCollections(
...
+// to a closed channel. In our current design, we intentionally ignore such cases.
+//
+// If any engine crashes, we treat it as a sign of possible state corruption,
+// and the node is expected to restart. Thus, this edge case is not handled explicitly.
+func (s *CollectionSyncer) OnCollectionDownloaded(id flow.Identifier, entity flow.Entity) {
+	err := s.pendingCollectionsHandler.Process(id, entity)
 	if err != nil {
-		s.logger.Error().Err(err).Msg("could not index collection after it has been downloaded")
-		return
+		s.logger.Warn().Err(err).Msg("failed to process pending collections")
```
Comment (peterargue) [inline engine/access/ingestion2/collection_syncer.go]: this is still using the log and continue pattern that we're trying to avoid. Typically, this is done within a `Process` method which returns an error. Since `OnCollectionDownloaded` is a `requester.HandleFunc` which does not return an error, we should just log a fatal here instead with a comment.
```suggestion
		// this is an unexpected error condition. The only expected error returned from Process
		// is for an unexpected type. since OnCollectionDownloaded is called from the requester
		// engine which is configured to only process collections, any error returned here indicates
		// a bug or state corruption.
		s.logger.Fatal().Err(err).Msg("failed to process pending collections")
		return
```

File: engine/access/ingestion2/collection_syncer.go [hunk 6]
```diff
@@ -145,6 +171,24 @@ func (s *CollectionSyncer) StartWorkerLoop(ctx irrecoverable.SignalerContext, re
...
+
+		case <-s.pendingCollectionsHandler.GetNotifier():
+			msg, ok := s.pendingCollections.Get()
+			if !ok {
+				ctx.Throw(fmt.Errorf("could not get pending collection"))
+			}
+
+			collection, ok := msg.Payload.(*flow.Collection)
+			if !ok {
+				ctx.Throw(fmt.Errorf("could not cast pending collection to *flow.Collection"))
```
Comment (peterargue) [inline engine/access/ingestion2/collection_syncer.go]: let's include more detail so it's easier to debug if this ever comes up
```suggestion
				ctx.Throw(fmt.Errorf("could not cast pending collection to *flow.Collection. got: %T", msg.Payload))
```

File: engine/access/ingestion2/collection_syncer.go [hunk 7]
```diff
@@ -405,17 +449,17 @@ func (s *CollectionSyncer) findLowestBlockHeightWithMissingCollections(
...
-
-	err := indexer.IndexCollection(collection, s.collections, s.transactions, s.logger, s.collectionExecutedMetric)
+// This function is a callback intended to be used by the requester engine.
+//
+// Note: You might wonder what happens if the ingestion engine crashes,
+// but the requester engine continues to invoke this callback and writes
+// to a closed channel. In our current design, we intentionally ignore such cases.
+//
+// If any engine crashes, we treat it as a sign of possible state corruption,
+// and the node is expected to restart. Thus, this edge case is not handled explicitly.
```
Comment (peterargue) [inline engine/access/ingestion2/collection_syncer.go]: I don't think this is accurate anymore
```suggestion
```

**Review by peterargue — APPROVED** [review]
