### PR TITLE
[DataAvailability] add criteria to websockets layer (events and account statuses)

### LINKED ISSUE #8331: [DataAvailability] Turn on integration & unit tests that were skipped due to active work on optimistic sync package
We skip some tests currently because they're broken and do not support the new logic of the execution result provider. We need to turn them on once the backends are ready and merged in. IT could be done as part of the appropriate issues/PRs. I created this issue to remind ourselves to do it.

### PR DESCRIPTION
**Pull request by illia-malachyn**
Closes #8331 #7658 #7657

- removed legacy tests
- rewrote handler_test.go to not inherit other test suite
- added execution state query arg to events/accounts args in websockets package

### CODE REVIEW

File: engine/access/rest/websockets/data_providers/args_validation.go [hunk 1]
```diff
@@ -1,57 +1,176 @@
...
+	executionStateQuery, ok := executionStateRaw.(map[string]interface{})
+	if !ok {
+		return httpmodels.ExecutionStateQuery{},
+			fmt.Errorf("'execution_state_query' must be a map: %w", ErrInvalidArgument)
+	}
+
+	agreeingExecutorsCountRaw, exists := executionStateQuery["agreeing_executors_count"]
+	if !exists {
+		out.AgreeingExecutorsCount = 0
+	} else {
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/args_validation.go]: this is the go type's default value, no need to explicitly set it
```suggestion
	if exists {
```

File: engine/access/rest/websockets/data_providers/args_validation.go [hunk 2]
```diff
@@ -1,57 +1,176 @@
...
+			return httpmodels.ExecutionStateQuery{},
+				fmt.Errorf("'agreeing_executors_count' must be a number: %w", errors.Join(err, ErrInvalidArgument))
+		}
+		out.AgreeingExecutorsCount = val
+	}
+
+	requiredExecutorIDsRaw, exists := executionStateQuery["required_executor_ids"]
+	if !exists {
+		out.RequiredExecutorIDs = nil
+	} else {
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/args_validation.go]:
```suggestion
	if exists {
```

File: engine/access/rest/websockets/data_providers/args_validation.go [hunk 3]
```diff
@@ -1,57 +1,176 @@
...
+				fmt.Errorf("'required_executor_ids' must be an array of strings: %w", errors.Join(err, ErrInvalidArgument))
+		}
+		// flow.IdentifierList is a []flow.Identifier, compatible with the target field type.
+		out.RequiredExecutorIDs = ids
+	}
+
+	includeExecutorMetadataRaw, exists := executionStateQuery["include_executor_metadata"]
+	if !exists {
+		out.IncludeExecutorMetadata = false
+	} else {
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/args_validation.go]:
```suggestion
	if exists {
```

**Review by AndriiDiachuk — APPROVED** [review]
