### PR TITLE
[Access] OK response should not contain error message

### LINKED ISSUE #7009: [Access] Empty error object in successful WebSocket subscription responce
## 🐞 Bug Report

If subscribe to any topic, the success response contains an empty error object:

```json
{
    "subscription_id": "a06381bf-9932-49e9-82b0-caad09e553bc",
    "error": {
        "code": 0,
        "message": ""
    },
    "action": "subscribe"
}
```

It should not be present at all in success responce.

### PR DESCRIPTION
**Pull request by illia-malachyn**
Branched off https://github.com/onflow/flow-go/pull/6907

- Pass object by pointer rather than by value, so that it is not encoded with zeros but omitted in JSON  
- Move data providers' models to `data providers` package. 
- Replace `Build()` function with factory method pattern `New...() `

Closes #7009  #7039

### CODE REVIEW

**Comment by illia-malachyn** [comment]
Some tests might fail because of https://github.com/onflow/flow-go/pull/6907

File: engine/access/rest/websockets/data_providers/blocks_provider.go [hunk 1]
```diff
@@ -88,8 +88,11 @@ func (p *BlocksDataProvider) Run() error {
...
 
-			var response models.BaseDataProvidersResponse
-			response.Build(p.ID(), p.Topic(), &block)
+			response := models.BaseDataProvidersResponse{
+				SubscriptionID: p.ID(),
+				Topic:          p.Topic(),
+				Payload:        &block,
+			}
 
 			return &response, nil
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/blocks_provider.go:97]: consider this for here and elsewhere
```suggestion
			return &models.BaseDataProvidersResponse{
				SubscriptionID: p.ID(),
				Topic:          p.Topic(),
				Payload:        &block,
			}, nil
```

**Review by peterargue — COMMENTED** [review]
added a few small comments, but otherwise looks good

File: engine/access/rest/websockets/data_providers/blocks_provider.go (hunk 1 above)
Comment (illia-malachyn) [reply engine/access/rest/websockets/data_providers/blocks_provider.go:97]: I intentionally kept it this way to improve readability. Naming the variable (`response` in this case) makes the code clearer, as it explicitly conveys what the `interface{}` value represents. Without it, a developer would need to infer the meaning from the struct itself. This small addition reduces cognitive load and makes the code more self-explanatory.
What do you think of it?

**Review by peterargue — APPROVED** [review]
