### PR TITLE
[Access] ws controller should recover from panics

### LINKED ISSUE #7036: [Access] Gorilla websocket connection type may panic. We should catch it
Currently, the Gorilla's `Connection` type panics if certain usage rules are violated, such as:
- Having multiple writers on a single [connection](https://github.com/gorilla/websocket/blob/main/conn.go#L759) 
- Not handling [read errors](https://github.com/gorilla/websocket/blob/main/conn.go#L1041)

While these rules are clear to "experienced" users, a new developer might unknowingly break them, leading to unexpected crashes.

**Proposal**:
Catch such panics and add a meaningful log about it. This will make life easier for the next dev.

### PR DESCRIPTION
**Pull request by illia-malachyn**
Closes #7036

### CODE REVIEW

File: engine/access/rest/websockets/controller.go [hunk 1]
```diff
@@ -220,6 +220,12 @@ func (c *Controller) configureKeepalive() error {
 // keepalive sends a ping message periodically to keep the WebSocket connection alive
 // and avoid timeouts.
 func (c *Controller) keepalive(ctx context.Context) error {
+	defer func() {
+		if r := recover(); r != nil {
```
Comment (peterargue) [inline engine/access/rest/websockets/controller.go:224]:
```suggestion
		// gracefully handle panics from github.com/gorilla/websocket
		if r := recover(); r != nil {
```

File: engine/access/rest/websockets/controller.go [hunk 2]
```diff
@@ -246,10 +252,11 @@ func (c *Controller) keepalive(ctx context.Context) error {
 // If no messages are sent within InactivityTimeout and no active data providers exist,
 // the connection will be closed.
 func (c *Controller) writeMessages(ctx context.Context) error {
-	inactivityTicker := time.NewTicker(c.inactivityTickerPeriod())
-	defer inactivityTicker.Stop()
-
-	lastMessageSentAt := time.Now()
+	defer func() {
+		if r := recover(); r != nil {
```
Comment (peterargue) [inline engine/access/rest/websockets/controller.go:256]:
```suggestion
		// gracefully handle panics from github.com/gorilla/websocket
		if r := recover(); r != nil {
```

File: engine/access/rest/websockets/controller.go [hunk 3]
```diff
@@ -308,6 +320,12 @@ func (c *Controller) inactivityTickerPeriod() time.Duration {
 // readMessages continuously reads messages from a client WebSocket connection,
 // validates each message, and processes it based on the message type.
 func (c *Controller) readMessages(ctx context.Context) error {
+	defer func() {
+		if r := recover(); r != nil {
```
Comment (peterargue) [inline engine/access/rest/websockets/controller.go:324]:
```suggestion
		// gracefully handle panics from github.com/gorilla/websocket
		if r := recover(); r != nil {
```

**Review by peterargue — APPROVED** [review]
