### PR TITLE
[Storage] Fix memory caches getting out of sync with db (BadgerDB & Pebble)

### LINKED ISSUE #7383: [Storage] Memory caches using concatenated IDs may contain items deleted from databases
Updates #7242
Related #7313

Currently, some memory caches that use concatenated IDs, etc., as keys can contain items that were already deleted from the database.

This problem is fixed in other memory caches (they use delete-by-key instead of delete-by-prefix):
- PR #7324
- delete-by-prefix was also fixed by PR 7324 but is commented out to avoid blocking PR
  (in case it is too slow and in case optimization discussions take longer than expected)

On Broadwell Xeon 2.2Ghz, deleting 5000 keys from a golang-lru cache with 10000 items takes:
- ~0.88 ms for delete-by-key (using 5000 keys for exact match deletion)
- ~1.63 ms for delete-by-prefix using 1000 prefixes (5 keys per prefix)
  - ~0.88 ms (delete 5K items) + ~0.75 ms (overhead of using prefixes)

NOTE: The 1.63 ms duration includes the unavoidable 0.88 ms with golang-lru (see below).  So if we optimize use of golang-lru, then we are optimizing the 0.75 ms portion of 1.63 ms and introducing tradeoffs.

If 1.63 ms is fast enough, then we can just use `RemoveFunc` approach (already implemented in PR #7324 but currently commented out).  It doesn't sacrifice speed of existing golang-lru functions to speedup the less frequent delete-by-prefix operation.

If 1.63 ms is too slow, then see below for more details and considerations for optimizing the 0.75 ms portion of the 1.63 ms for delete-by-prefix.

Either way, we should probably run more benchmarks and at least identify reasonable upper bound(s) we should be enforcing on the cache item limit configuration flag(s). Some flags shouldn't be unbounded.

### Delete-by-key vs Delete-by-prefix

UPDATE: I ran benchmarks on Sunday, May 11, 2025 (to prep for May 12 meeting, not to optimize) and added this section.

If we already have a set of 5000 keys to delete, then removing 5000 items by key from a golang-lru cache containing 10000 items takes about 0.9 ms on Broadwell Xeon 2.2Ghz.

Sometimes we only have prefixes instead of specific keys to delete. For example, we may have 1000 prefixes (e.g., block ids) during pruning and each prefix might match an average of about 4-5 keys we want to delete.

Given this, deleting 5000 items by prefix from unmodified golang-lru containing 10000 items will require more than 0.9ms.  Benchmark code:

```Go
for range b.N
    // Setup and start timer:
    // - Create 10K-item cache.
    // - From 1000 block ids (prefixes), create slice of 5K keys.
    // ...
    b.StartTimer()

    // On Broadwell Xeon 2.2Ghz, this part takes about 0.9 ms, so:
    //   ???.? ms to gather 5K keys from 1000 prefixes
    //     0.9 ms to Remove() 5K keys (remove by exact match)
    //   =========
    //   ???.? ms because gathering 5K keys from 1000 block ids takes time

    for _, id := range removeIDs {
        cache.Remove(id)  // remove key by exact match
    } 
}
```

Using the unoptimized `RemoveFunc` feature I added to golang-lru takes about 1.6 ms for delete-by-prefix:
- 10000 items in the cache
- 1000 prefixes (block ids)
- 5000 items deleted (5 items matched per prefix)
- ~1.6 ms duration on Broadwell Xeon 2.2Ghz
  - ~0.9 ms of this is unavoidable with golang-lru deleting 5K items from 10K cache
  - unoptimized `RemoveFunc` required no modifications to existing golang-lru functions

Using golang-lru `RemoveFunc()` iterates just once over the cache, gets the prefix from each item's key, and looks up each prefix in a map of prefixes to remove.  Benchmark code:

```Go
for range b.N
    // Create 10K-item cache.
    // NOTE: We avoid gathering 5K keys from 1000 prefixes (block ids).
    // ...
    b.StartTimer()

    cache.RemoveFunc(func(key string) bool {
        keyPrefix := key[:64]
        return removePrefixes[keyPrefix]  // item is removed from cache if true
     })
     
     // On Broadwell Xeon 2.2Ghz, this takes about:
     //  ~0.00 ms very fast to gather prefixes (we already have block ids).
     //   1.63 ms to remove-by-prefix 5K keys.
     //   =======
     //   1.63 ms
}
```

See fxamacker/golang-lru for [implementation details](https://github.com/hashicorp/golang-lru/compare/main...fxamacker:golang-lru:fxamacker/add-removefunc-to-simplelru) about `RemoveFunc()`.

### Next Steps

We can either:
- leave deleted items in the cache for some specific senarios (see Notes section below), or
- use `RemoveFunc()` if it is fast enough for delete-by-prefix during database pruning, etc.
- invest time to look into optimizing delete-by-prefix (See Notes section below)

### Notes

For memory caches using concatenated IDs as keys, there are multiple approaches to evaluate. They include (in no particular order):

A.  Leaving deleted items in the cache and relying on a different layer of code to prevent calls to get items from the cache if some criteria isn't met (e.g., items below the pruned height as suggested by Leo).  However, leaving deleted items in the cache can invite future bugs, especially as different layers of code (e.g., storage vs non-storage layer, etc.) get maintained by different people. Also, leaving garbage in the LRU cache can increase cache misses, cause non-garbage items to be evicted earlier than necessary, and wastes memory.

B.  Removing items by prefix (block id) from unmodified golang-lru cache is too slow.  Using a minimally modified golang-lru cache to provide `RemoveFunc` is still too slow (because it avoids further optimizations that require changing existing golang-lru functions).  Batching prefixes can make using `RemoveFunc` faster.  However, this approach is still too slow (if 1.6 ms is too slow for removing 5K items from 10K golang-lru by using 1K prefixes), especially if cache item limit is 10K by default and is configurable by flag.

C.  Removing items by key (e.g., block id + transaction id) can be faster if we have the list of keys to delete from cache (rather than a list of prefixes) but there are tradeoffs.  E.g., using the most efficient built-in way to delete records from Pebble doesn't provide list of deleted keys, so the list of deleted keys need to be retrieved by prefix using db.Iterator, etc.

D. Changing the cache key from the concatenation of IDs to prefix.  This approach doesn't require modifying golang-lru.  However, this approach can slow down retrieval, which is more frequent than removal.

E.  Maintaining a prefix index for cached records.  This index map can be used to remove keys by exact match, which is faster than removing by prefix.  However, this approach adds overhead to nearly all operations that modifies the cache: reading, inserting, deleting records from database and also evicting items from the cache.  This adds memory overhead linear to cache size limit, but that should be OK for a 10K-item cache.  To be efficient, this may or may not benefit from direct modifications to golang-lru cache (look into this as part of evaluation).

F. Replace golang-lru cache with an existing production-quality cache that is optimized for fast delete-by-prefix. A quick search didn't find one (look into this as part of evaluation).

G. Maintaining an index of removed prefixes.  The index can be used to filter out deleted items before retrieving from the cache.  This approach can small overhead to removal and retrieval.  It also adds some memory overhead than can be pruned periodically to avoid unbound growth.  To be efficient, this may or may not benefit from direct modifications to golang-lru cache (look into this as part of evaluation).

### PR DESCRIPTION
**Pull request by fxamacker**
Closes #7383
Related to #7313 

This PR uses the new `GroupCache` LRU created for deleting group of keys when we only have the prefix that would match the keys we want to delete: 
- https://github.com/fxamacker/golang-lru/pull/1

Currently, some memory caches that use concatenated IDs, etc., as keys can contain items that were already deleted from the database.

For use cases where we know the exact key to be deleted, the problem was already solved by flow-go #7324 and delete-by-key is fast enough (it is the max possible delete speed of hashicorp/golang-lru).

Unfortunately, deleting a set of keys without knowing the exact keys to delete would be too slow, especially as the cache size grows. As an added risk, the cache size is configurable by flag.

This PR uses `GroupCache` to retain the fast speed of `Get` while also allowing the delete-by-group performance to be relatively stable even as number of total items in the cache grows. The trade-off is to use some extra memory.  

Previously, using the old approach of `RemoveFunc` would be roughly 2x slower than delete-by-key and become even slower than that if the cache size is larger.

By comparison, `GroupCache` is only about 17% slower than delete-by-key (the max possible speed) when deleting 5,000 keys in groups of 5 (i.e., each key prefix matching 5 keys) with cache size of 10,000.
```
delete-by-key  delete-by-group
697.1µ ± 11%   814.7µ ± 1%      +16.86% (p=0.000 n=20)
```

Preliminary benchmarks show `GroupCache` does not slow down when deleting the same number of keys by group as cache size grows.
```
cache_size_1,000    8565 ns/op
cache_size_2,000    9709 ns/op
cache_size_3,000    9451 ns/op
cache_size_4,000   10370 ns/op
cache_size_5,000   10073 ns/op
cache_size_10,000   8268 ns/op
```

These preliminary results are informal (run on a desktop with GUI, etc.).

Extra memory overhead consists of `map[group]map[key]struct{}`, which contains mappings of group name and cached keys.  So extra memory used depends on size of the keys and number of keys in the cache.

### Timeline & Status Updates

- [flow-go#7383#comment-3058481511](https://github.com/onflow/flow-go/issues/7383#issuecomment-3058481511)
- [flow-go#7383#comment-3078688125](https://github.com/onflow/flow-go/issues/7383#issuecomment-3078688125)

### CODE REVIEW

File: storage/operation/badgerimpl/writer.go [hunk 1]
```diff
@@ -196,3 +200,18 @@ func (b *ReaderBatchWriter) DeleteByRange(globalReader storage.Reader, startPref
...
+		return
+	}
+	if b.values == nil {
+		b.values = make(map[string]any)
+	}
+	b.values[key] = value
+}
+
+func (b *ReaderBatchWriter) Value(key string) any {
+	return b.values[key]
```
Comment (zhangchiqing) [inline storage/operation/badgerimpl/writer.go]: b.values might be nil, no?

Maybe return `(any, bool)` to indicate whether there is value stored

File: storage/store/group_cache_test.go [hunk 2]
```diff
@@ -0,0 +1,218 @@
...
+		for range groupCount {
+			var groupID flow.Identifier
+			_, _ = rand.Read(groupID[:])
+
+			groupIDs = append(groupIDs, groupID)
+
+			for range itemCountPerGroup {
+				var itemID TwoIdentifier
+				_, _ = rand.Read(itemID[:])
+				copy(itemID[:], groupID[:])
```
Comment (zhangchiqing) [inline storage/store/group_cache_test.go]:
```suggestion
				// overwrite the first Identifier of item ID with group ID
				copy(itemID[:], groupID[:])
```

File: storage/store/group_cache_test.go [hunk 3]
```diff
@@ -0,0 +1,218 @@
...
+			if err != nil {
+				return nil, err
+			}
+			return val, nil
+		}
+
+		cache := mustNewGroupCache(
+			metrics.NewNoopCollector(),
+			"test",
+			func(id TwoIdentifier) flow.Identifier { return flow.Identifier(id[:flow.IdentifierLen]) },
```
Comment (zhangchiqing) [inline storage/store/group_cache_test.go]:
```suggestion
			// group by the first Identifier
			func(id TwoIdentifier) flow.Identifier { return flow.Identifier(id[:flow.IdentifierLen]) },
```

File: storage/store/transaction_results.go [hunk 4]
```diff
@@ -172,31 +198,43 @@ func (tr *TransactionResults) RemoveByBlockID(blockID flow.Identifier) error {
...
+				for id := range blockIDs {
+					blockIDsInSlice = append(blockIDsInSlice, id)
+				}
+
+				tr.cache.RemoveGroups(blockIDsInSlice)
+			}
+		}
+	})
+
+	saveBlockIDInBatchData(batch, batchDataKey, blockID)
```
Comment (zhangchiqing) [inline storage/store/transaction_results.go:234]: Why do we need to save block id to the batch object? Can we use clojure?

```
	storage.OnCommitSucceed(batch, func() {
		tr.cache.RemoveGroup(blockID)
	})
```

**Comment by fxamacker** [comment]
@zhangchiqing welcome back again and thanks for reviewing this yesterday!

I need to refresh memory on this PR before resolving feedback because it has been 21 days.

I will circle back to this PR right after [wrapping up some items](https://github.com/onflow/flow-go/issues/7573#issuecomment-3162242757) in public key deduplication (e.g., creating and running migration to see actual memory use and duration, so we know what `nworkers` to use on `m3`).

**Comment by fxamacker** [comment]
Hey @zhangchiqing 👋 just a heads up that we might include this in upcoming mainnet spork next month.

The issue (#7383) that this PR fixes was moved to `Cycle Backlog` status on Aug 29, 2025, but I asked about this a few times and was told a couple days ago (Tuesday, Sep. 23) that we might be able to include this in the upcoming mainnet.

File: storage/store/transaction_results.go (hunk 4 above)
Comment (fxamacker) [reply storage/store/transaction_results.go:234]: > Why do we need to save block id to the batch object? Can we use clojure?

We save block id to batch object so that we can call `cache.RemoveGroups()` to remove all blocks with one cache lock.

Since `cache` functions use mutex under the hood, it would lock N times if we remove N groups separately.

And I designed `cache.RemoveGroups()` to allow us to lock just once instead of N times.

File: storage/operation/badgerimpl/writer.go [hunk 5]
```diff
@@ -21,6 +21,10 @@ type ReaderBatchWriter struct {
 
 	// for executing callbacks after the batch has been flushed, such as updating caches
 	callbacks *operation.Callbacks
+
+	// values store value for this batch.
+	// NOTE: b.values is only initialized when needed.
```
Comment (peterargue) [inline storage/operation/badgerimpl/writer.go]: I found some of the logic around handling the uninitialized map unintuitive. I also see why we'd want to avoid allocating a map within a structure that almost never needs it and may be created hundreds of times per second.

Can you expand the docs here to explain why the just in time initialization is needed. Then add some comments to the `SetValue` and `Value` methods reminding readers of the expected behavior when interacting with a `nil` map.

File: storage/operations.go [hunk 6]
```diff
@@ -147,6 +147,14 @@ type ReaderBatchWriter interface {
...
 	// The error parameter is the error returned by the batch update.
 	AddCallback(func(error))
+
+	// SetValue stores the given value by the given key in this batch.
+	// Stored value can be retrieved by the same key via Value().
+	SetValue(key string, value any)
+
+	// Value returns the value associated with this batch for the given key and true if key exists,
+	// or nil and false if key doesn't exist.
+	Value(key string) (any, bool)
```
Comment (peterargue) [inline storage/operations.go]: from an API perspective, it seems strange to add caching specific methods into the batch writer. it took me a while to convince myself that it makes sense given the usecase you are handling.

Can you expand on this documentation to include more about the expected usage and examples of where it's used today. it may also help to reframe these as `SetMetadata` or `SetScratchpad` to help paint a clearer picture of intended usage.

File: storage/store/cache_test.go [hunk 7]
```diff
@@ -2,24 +2,63 @@ package store
...
+	resourceName string,
+	groupFromKey func(K) G,
+	options ...func(*Cache[K, V]),
+) *GroupCache[G, K, V] {
+	cache, err := newGroupCache(collector, resourceName, groupFromKey, options...)
+	if err != nil {
+		panic(err)
+	}
+	return cache
+}
```
Comment (peterargue) [inline storage/store/cache_test.go:39]: nit: you can use a requires instead of a panic. I think that would place nicer with the test framework.
```suggestion
func newGroupCache[G comparable, K comparable, V any](
	t testing.TB,
	collector module.CacheMetrics,
	resourceName string,
	groupFromKey func(K) G,
	options ...func(*Cache[K, V]),
) *GroupCache[G, K, V] {
	cache, err := newGroupCache(collector, resourceName, groupFromKey, options...)
	requires.NoError(t, err)
	return cache
}
```

File: storage/store/group_cache_test.go [hunk 8]
```diff
@@ -0,0 +1,218 @@
...
+		)
+
+		const groupCount = 5
+		const itemCountPerGroup = 5
+
+		groupIDs := make([]flow.Identifier, 0, groupCount)
+		keyValuePairs := make(map[TwoIdentifier][]byte)
+		for range groupCount {
+			var groupID flow.Identifier
+			_, _ = rand.Read(groupID[:])
```
Comment (peterargue) [inline storage/store/group_cache_test.go]:
```suggestion
			groupID := unittest.IdentifierFixture()
```

File: storage/store/transaction_results.go [hunk 9]
```diff
@@ -81,19 +89,37 @@ func NewTransactionResults(collector module.CacheMetrics, db storage.DB, transac
...
+	cache, err := newGroupCache(
+		collector,
+		metrics.ResourceTransactionResults,
+		FirstIDFromTwoIdentifier,
+		withLimit[TwoIdentifier, flow.TransactionResult](transactionResultsCacheSize),
+		withStore(noopStore[TwoIdentifier, flow.TransactionResult]),
+		withRetrieve(retrieve),
+	)
+	if err != nil {
+		panic(err)
```
Comment (peterargue) [inline storage/store/transaction_results.go]: can we return an error instead of panicking?

File: storage/store/transaction_results.go [hunk 10]
```diff
@@ -172,31 +198,43 @@ func (tr *TransactionResults) RemoveByBlockID(blockID flow.Identifier) error {
...
-			keyPrefix := KeyFromBlockID(blockID)
-
-			tr.cache.RemoveFunc(func(key string) bool {
-				return strings.HasPrefix(key, keyPrefix)
-			})
-		})
-	*/
+	const batchDataKey = "TransactionResults.BatchRemoveByBlockID"
+
+	storage.OnCommitSucceed(batch, func() {
```
Comment (peterargue) [inline storage/store/transaction_results.go:215]: can you add a comment about what's going on here and why it's needed?

File: storage/operations.go (hunk 6 above)
Comment (fxamacker) [reply storage/operations.go]: > Can you expand on this documentation to include more about the expected usage and examples of where it's used today.

Done. I added an example of the intended first usage but this can also be used to store any data or metadata that needs to be accessed within the scope of individual objects implementing  `ReaderBatchWriter`.

> it may also help to reframe these as `SetMetadata` or `SetScratchpad` to help paint a clearer picture of intended usage.

Good point. I initially took inspiration from Go's [Context.WithValue](https://pkg.go.dev/context#WithValue) by using the name `Value`, but that is too general as you point out.  I also like `Metadata` as you suggested, but it is a bit too limiting.

To resolve this, I renamed "Value" to `ScopedValue`, so we have `SetScopedValue`, `ScopedValue`, etc. after seeing mention of scoped value inside the Go runtime docs for `Context`.

File: storage/operation/writes_test.go [hunk 11]
```diff
@@ -574,3 +574,121 @@ func getFolderSize(t testing.TB, dir string) int64 {
 
 	return size
 }
+
+func TestBatchValue(t *testing.T) {
+	const key = "key1"
+
+	dbtest.RunWithDB(t, func(t *testing.T, db storage.DB) {
+		t.Run("no data", func(t *testing.T) {
+			b := db.NewBatch()
```
Comment (zhangchiqing) [inline storage/operation/writes_test.go]: Better to use `db.WithReaderBatchWriter`, so that we don't need to call `b.Close` and `b.Commit`

File: storage/operation/badgerimpl/writer.go [hunk 12]
```diff
@@ -21,6 +21,17 @@ type ReaderBatchWriter struct {
 
 	// for executing callbacks after the batch has been flushed, such as updating caches
 	callbacks *operation.Callbacks
+
+	// values contains the values for this batch.
+	// The values map is set using SetValue(key, value) and retrieved using Value(key).
```
Comment (peterargue) [inline storage/operation/badgerimpl/writer.go]:
```suggestion
	// The values map is set using SetScopedValue(key, value) and retrieved using ScopedValue(key).
```

File: storage/store/group_cache.go [hunk 13]
```diff
@@ -0,0 +1,48 @@
+package store
+
+import (
+	lru "github.com/fxamacker/golang-lru/v2"
+
+	"github.com/onflow/flow-go/module"
+)
+
+type GroupCache[G comparable, K comparable, V any] struct {
```
Comment (zhangchiqing) [inline storage/store/group_cache.go:16]:
```suggestion
// GroupCache extends the Cache with a secondary index on groupID, 
// the groupID can be used to remove cached items by group. 
// a common use case is to cache data indexed by block ID, and can be 
// removed by block ID.
type GroupCache[G comparable, K comparable, V any] struct {
```

File: storage/operation/pebbleimpl/writer.go [hunk 14]
```diff
@@ -21,6 +21,10 @@ type ReaderBatchWriter struct {
 
 	// for executing callbacks after the batch has been flushed, such as updating caches
 	callbacks *operation.Callbacks
+
+	// values store value for this batch.
+	// NOTE: b.values is only initialized when needed.
```
Comment (peterargue) [inline storage/operation/pebbleimpl/writer.go]:
```suggestion
	// values contains the values for this batch.
	// The values map is set using SetScopedValue(key, value) and retrieved using ScopedValue(key).
	// Initialization of the values map is deferred until it is needed, because
	// ReaderBatchWriter is created frequently to update the database, but
	// this values map is used infrequently to save data for batch operations.
	// For example, store.TransactionResults.BatchRemoveByBlockID() saves batch
	// removed block IDs in values map, and retrieves the batch removed block
	// IDs in OnCommitSucceed() callback.  This allows locking just once,
	// instead of locking TransactionResults cache for every removed block ID.
```

File: storage/store/group_cache.go [hunk 15]
```diff
@@ -0,0 +1,48 @@
...
+	return &GroupCache[G, K, V]{
+		Cache: c,
+	}, nil
+}
+
+func (c *GroupCache[G, K, V]) RemoveGroup(group G) int {
+	return c.cache.(*lru.GroupCache[G, K, V]).RemoveGroup(group)
+}
+
+func (c *GroupCache[G, K, V]) RemoveGroups(groups []G) int {
```
Comment (zhangchiqing) [inline storage/store/group_cache.go:57]: Please add comments about the returned value

**Review by zhangchiqing — APPROVED** [review]
Looks good. Thanks for the fix.

File: storage/store/transaction_results.go [hunk 16]
```diff
@@ -81,24 +89,42 @@ func NewTransactionResults(collector module.CacheMetrics, db storage.DB, transac
...
+	cache, err := newGroupCache(
+		collector,
+		metrics.ResourceTransactionResults,
+		FirstIDFromTwoIdentifier,
+		withLimit[TwoIdentifier, flow.TransactionResult](transactionResultsCacheSize),
+		withStore(noopStore[TwoIdentifier, flow.TransactionResult]),
+		withRetrieve(retrieve),
+	)
+	if err != nil {
+		return nil, err
```
Comment (peterargue) [inline storage/store/transaction_results.go]:
```suggestion
		return nil, fmt.Errorf("failed to create group cache: %w", err)
```

File: storage/store/transaction_results.go [hunk 17]
```diff
@@ -81,24 +89,42 @@ func NewTransactionResults(collector module.CacheMetrics, db storage.DB, transac
...
+	indexCache, err := newGroupCache(
+		collector,
+		metrics.ResourceTransactionResultIndices,
+		IDFromIdentifierAndUint32,
+		withLimit[IdentifierAndUint32, flow.TransactionResult](transactionResultsCacheSize),
+		withStore(noopStore[IdentifierAndUint32, flow.TransactionResult]),
+		withRetrieve(retrieveIndex),
+	)
+	if err != nil {
+		panic(err)
```
Comment (peterargue) [inline storage/store/transaction_results.go]:
```suggestion
		return nil, fmt.Errorf("failed to create group cache: %w", err)
```
