### PR TITLE
try to update to new middleware

### LINKED ISSUE #5739: update go-grpc-middleware to not prerelease
## 🐞 Bug Report

flow-go currently imports v2.0.0-rc.2 of grpc-middleware. the api in this version was not stable and has changed a lot since. 

## What is the severity of this bug?

**Should have:** 

## Expected behaviour

Upgrading this to a new version and reimplementing the grpc middleware with the stable api makes the library a lot more robust. In find we indirectly import flow-go and we would like to use newer features of grpc-middleware like timeouts and the new api.

### PR DESCRIPTION
**Pull request by bjartek**
Updating the grpc middleware to v2.1.0 and use the new code for the logging interceptor. 

note that the 

```	tagsInterceptor := tags.UnaryServerInterceptor(tags.WithFieldExtractor(tags.CodeGenRequestFieldExtractor))
``` 

was removed in the stable api because "it was not beeing used", if this is used here and we want to do this we have to put the fields into context and then inject them in. 

Fixes #5739

### CODE REVIEW

File: engine/common/rpc/logging_interceptor.go [hunk 1]
```diff
@@ -19,7 +20,30 @@ func customClientCodeToLevel(c codes.Code) logging.Level {
 
 // LoggingInterceptor creates the logging interceptors to log incoming GRPC request and response (minus the payload body)
 func LoggingInterceptor(log zerolog.Logger) []grpc.UnaryServerInterceptor {
-	tagsInterceptor := tags.UnaryServerInterceptor(tags.WithFieldExtractor(tags.CodeGenRequestFieldExtractor))
-	loggingInterceptor := logging.UnaryServerInterceptor(grpczerolog.InterceptorLogger(log), logging.WithLevels(customClientCodeToLevel))
-	return []grpc.UnaryServerInterceptor{tagsInterceptor, loggingInterceptor}
+	//this code gen extractor was removed, is this needed? if it is we need to use context for passing these along or so they say
+	//
+	//tagsInterceptor := tags.UnaryServerInterceptor(tags.WithFieldExtractor(tags.CodeGenRequestFieldExtractor))
```
Comment (peterargue) [inline engine/common/rpc/logging_interceptor.go:25]: I think it's safe to remove these. I can't find any evidence we were using it.
```suggestion
```

**Review by peterargue — APPROVED** [review]
looks good. Thanks for the improvement!

I think the lint error can be fixed by updating line 16 with `logging.LevelDebug`

**Review by kc1116 — APPROVED** [review]

**Comment by bjartek** [comment]
fixed linter and applies suggestions. PTAL.
