### PR TITLE
Fix data race in account grouping for account based migration

### LINKED ISSUE #5485: Payload grouping has data races
## 🐞 Bug Report

`GroupPayloadsByAccount` has data races.

## What is the severity of this bug?

**Critical:** We can't do anything if this isn't actioned immediately (product doesn't function without this, it's blocking us or users, or it resolves a high severity security issue). One person should look at this right now. 

## Reproduction steps

Steps to reproduce the behaviour:

1. Build util binary with race detector enabled
2. Run account-based migration with worker count >1 

- [x] I followed these steps and was able to reproduce the issue

## Expected behaviour

The race detector should not report any errors.

## Screenshots

<details>
<summary>Report</summary>
```
==================
WARNING: DATA RACE
Write at 0x00c31072dd50 by goroutine 212:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:252 +0x1a9
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:231 +0xcd

Previous write at 0x00c31072dd50 by goroutine 213:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:252 +0x1a9
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func2()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:235 +0xcd

Goroutine 212 (running) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:230 +0x34a
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24

Goroutine 213 (running) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:234 +0x4ce
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24
==================
==================
WARNING: DATA RACE
Write at 0x00c00ccc2108 by goroutine 213:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:274 +0x3ef
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func2()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:235 +0xcd

Previous read at 0x00c00ccc2108 by goroutine 212:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:252 +0x1a9
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:231 +0xcd

Goroutine 213 (running) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:234 +0x4ce
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24

Goroutine 212 (running) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:230 +0x34a
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24
==================
==================
WARNING: DATA RACE
Write at 0x00c313590328 by goroutine 212:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:271 +0x37a
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:231 +0xcd

Previous write at 0x00c313590328 by goroutine 213:
  runtime.slicecopy()
      /opt/homebrew/Cellar/go@1.20/1.20.12/libexec/src/runtime/slice.go:310 +0x0
  github.com/onflow/flow-go/cmd/util/ledger/util.mergeInto()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:252 +0x1a9
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:240 +0x525
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads.func2()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:235 +0xcd

Goroutine 212 (running) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:230 +0x34a
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24

Goroutine 213 (finished) created at:
  github.com/onflow/flow-go/cmd/util/ledger/util.sortPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:234 +0x4ce
  github.com/onflow/flow-go/cmd/util/ledger/util.GroupPayloadsByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/util/payload_grouping.go:102 +0x12e
  github.com/onflow/flow-go/cmd/util/ledger/migrations.MigrateByAccount()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:82 +0x124
  github.com/onflow/flow-go/cmd/util/ledger/migrations.NewAccountBasedMigration.func1()
      /Users/bastian/Documents/work/flow-go/cmd/util/ledger/migrations/account_based_migration.go:52 +0x10f
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.migratePayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:320 +0x28c
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.extractExecutionStateFromPayloads()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/execution_state_extract.go:232 +0x21b
  github.com/onflow/flow-go/cmd/util/cmd/execution-state-extract.run()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/execution-state-extract/cmd.go:296 +0x1384
  github.com/spf13/cobra.(*Command).execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xf01
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x63a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/bastian/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x3c
  github.com/onflow/flow-go/cmd/util/cmd.Execute()
      /Users/bastian/Documents/work/flow-go/cmd/util/cmd/root.go:47 +0x25
  main.main()
      /Users/bastian/Documents/work/flow-go/cmd/util/main.go:8 +0x24
==================
``
</details>


## Specifications

- System: Linux
- Go: 1.20

### PR DESCRIPTION
**Pull request by fxamacker**
Closes #5485
Updates https://github.com/onflow/cadence/issues/3096

This fixes data race in account grouping.

While at it, also added test to reproduce the data race.

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
👏

File: cmd/util/ledger/util/payload_grouping.go [hunk 1]
```diff
@@ -177,17 +177,17 @@ func (s sortablePayloads) Swap(i, j int) {
 	s[i], s[j] = s[j], s[i]
 }
 
-func (s sortablePayloads) FindNextKeyIndex(i int) int {
+func (s sortablePayloads) FindNextKeyIndexUntil(i int, upperBound int) int {
```
Comment (janezpodhostnik) [inline cmd/util/ledger/util/payload_grouping.go:180]: ah, I see, Good catch!

**Review by janezpodhostnik — APPROVED** [review]
