### PR TITLE
Return error if --state-stream-addr no configured.

### LINKED ISSUE #7005: [Access] Crash when subscribe to "event" topic via new WebSockets
## Context

When trying to subscribe for events using the next message:
```json
{
    "action": "subscribe",
    "topic": "events"
}
```
Access node crash with next stacktrace:
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22238a4]

goroutine 2788655 [running]:
github.com/onflow/flow-go/engine/access/state_stream/backend.(*StateStreamBackend).SubscribeEventsFromLatest(0x412ac5?, {0x3380290?, 0xc12462e910?}, {0x0, 0xc11948a5a0, 0xc11948a5d0, 0xc11948a600, 0xc11948a630})
        <autogenerated>:1 +0x44
github.com/onflow/flow-go/engine/access/rest/websockets/data_providers.(*EventsDataProvider).createSubscription(0xc102a9b480, {0x3380290, 0xc12462e910}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
        /app/engine/access/rest/websockets/data_providers/events_provider.go:131 +0xfe
github.com/onflow/flow-go/engine/access/rest/websockets/data_providers.NewEventsDataProvider({0x3380290, 0xc11a4216d0}, {{0x336ca10, 0xc00142c440}, 0xff, {0x335bce0, 0xc000e4c320}, {0xc145af3800, 0x71, 0x1f4}, ...}, ...)
        /app/engine/access/rest/websockets/data_providers/events_provider.go:72 +0x48c
github.com/onflow/flow-go/engine/access/rest/websockets/data_providers.(*DataProviderFactoryImpl).NewDataProvider(0xc233ac7080?, {0x3380290, 0xc11a4216d0}, {0xc103130690, 0x78dd59?}, {0xc28edff50a, 0x38?}, 0xc128a40d78?, 0x78e07a?)
        /app/engine/access/rest/websockets/data_providers/factory.go:109 +0x24e
github.com/onflow/flow-go/engine/access/rest/websockets.(*Controller).handleSubscribe(0xc233ac7080, {0x3380290, 0xc11a4216d0}, {{{0x0, 0x0}, {0xc28edff500, 0x9}}, {0xc28edff50a, 0x6}, 0x0})
        /app/engine/access/rest/websockets/controller.go:429 +0x24c
github.com/onflow/flow-go/engine/access/rest/websockets.(*Controller).handleMessage(0xc233ac7080, {0x3380290, 0xc11a4216d0}, {0xc223f4ab00, 0x34, 0x40})
        /app/engine/access/rest/websockets/controller.go:375 +0x1c5
github.com/onflow/flow-go/engine/access/rest/websockets.(*Controller).readMessages(0xc233ac7080, {0x3380290, 0xc11a4216d0})
        /app/engine/access/rest/websockets/controller.go:350 +0xd6
github.com/onflow/flow-go/engine/access/rest/websockets.(*Controller).HandleConnection.func3()
        /app/engine/access/rest/websockets/controller.go:182 +0x1f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2788706
        /go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96
```

### PR DESCRIPTION
**Pull request by illia-malachyn**
Data providers now check if state stream api is not nil. Improved error messages for clients as well.

Closes #7005 #7008

### CODE REVIEW

File: engine/access/rest/websockets/data_providers/events_provider.go [hunk 1]
```diff
@@ -54,6 +54,11 @@ func NewEventsDataProvider(
 		heartbeatInterval: heartbeatInterval,
 	}
 
+	if p.stateStreamApi == nil {
+		logger.Debug().Msg("state stream api is nil. cannot stream events")
+		return nil, fmt.Errorf("this acess node is configured with no state stream api. cannot stream events")
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/events_provider.go:59]:
```suggestion
		return nil, fmt.Errorf("this access node does not support streaming events")
```

File: engine/access/rest/websockets/data_providers/account_statuses_provider.go [hunk 2]
```diff
@@ -55,6 +55,12 @@ func NewAccountStatusesDataProvider(
 		heartbeatInterval: heartbeatInterval,
 	}
 
+	if p.stateStreamApi == nil {
+		logger.Debug().Msg("state stream api is nil. cannot stream account statuses")
+		return nil, fmt.Errorf("this acess node is configured with no state stream api. " +
+			"cannot stream account statuses")
```
Comment (peterargue) [inline engine/access/rest/websockets/data_providers/account_statuses_provider.go:61]:
```suggestion
		return nil, fmt.Errorf("this access node does not support streaming account statuses")
```

File: engine/access/rest/websockets/controller.go [hunk 3]
```diff
@@ -315,20 +315,22 @@ func (c *Controller) readMessages(ctx context.Context) error {
 				return err
 			}
 
+			err = wrapErr("error reading message", err)
```
[the remark this answers is not in the document]
Comment (peterargue) [reply engine/access/rest/websockets/controller.go:318]: +1. I think we should use the standard syntax instead of inventing a new method to do it.

**Review by peterargue — COMMENTED** [review]
added a few small comments, but otherwise this looks good

**Review by peterargue — APPROVED** [review]
